### ISSUE TITLE
Learn React native

### ISSUE THREAD

**Issue by shahwan42** [egypt-shops/xshop-mobile#1]
- [x] install RN (Android SDK, etc)
- [x] use vs code with its extensions (setup your environment to be ready for development)
- [ ] create a dummy project and share its APK with us

**Comment by shahwan42** [comment]
@Mohamed-sattar you too, do this issue, sorry can't assign more than one person, free GitHub :3

**Comment by shahwan42** [comment]
@MhmoudRaslan @xc0rv0 @Mohamed-sattar Give me an update about your progress please...

**Comment by 0xC0rv0** [comment]
Installed react , android studio , intialized Awesome project  faced some problems and working on it 
I apologise for the delay. Have an exam on 31 aug and i will be completely into the project
